export const types={
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGIN_FAIL:'LOGIN_FAIL',
    LOGOUT_SUCCESS:'LOGOUT_SUCCESS',
    LOAD_NOTICES_SUCCESS:'LOAD_NOTICES_SUCCESS',
    LOAD_NOTICES_ERROR:'LOAD_NOTICES_ERROR',
    LOAD_ACCOUNT_SUCCESS:'LOAD_ACCOUNT_SUCCESS'

}